#!/bin/bash

LIBRARY_DIR=$OUTPUT_DIR/$LIBRARY
LIBRARY_PREFIX=$LIBRARY_DIR/$LIBRARY
OUT_BAM=$LIBRARY_PREFIX.aligned.bam
MAGECK_OUT_PREFIX=$LIBRARY_PREFIX

mkdir -p $LIBRARY_DIR

SGRNA_LIST_PREFIX=$REFERENCES_DIR/$SGRNA_LIST_NAME # also same as bt2 index prefix
SGRNA_LIST_FILE=$SGRNA_LIST_PREFIX.txt
SGRNA_FASTA=$SGRNA_LIST_PREFIX.fa

mkdir -p $REFERENCES_DIR

# count reads for sgRNAs
mageck count -l $SGRNA_LIST_FILE -n $MAGECK_OUT_PREFIX --sample-label "$LIBRARY" --fastq $OUT_BAM
