#!/bin/bash

SAMPLE_DIR=$OUTPUT_DIR/$SAMPLE
SAMPLE_PREFIX=$SAMPLE_DIR/$SAMPLE
OUT_BAM=$SAMPLE_PREFIX.aligned.bam
MAGECK_OUT_PREFIX=$SAMPLE_PREFIX

mkdir -p $SAMPLE_DIR

SGRNA_LIST_PREFIX=$REFERENCES_DIR/$SGRNA_LIST_NAME # also same as bt2 index prefix
SGRNA_LIST_FILE=$SGRNA_LIST_PREFIX.txt
SGRNA_FASTA=$SGRNA_LIST_PREFIX.fa

mkdir -p $REFERENCES_DIR

# count reads for sgRNAs
mageck count -l $SGRNA_LIST_FILE -n $MAGECK_OUT_PREFIX --sample-label "$SAMPLE" --fastq $OUT_BAM
